### PR TITLE
Spectral Clustering

### PR DESCRIPTION
**Pull request by arpitsomani8**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Is dendrogram required for this cluster ??

**Comment by Thilakraj1998** [comment]
Suggestion:
1. can we add any description/ any methodology to understand how to select number for cluster in Spectral Clustering technique

**Comment by arpitsomani8** [comment]
sure

**Comment by arpitsomani8** [comment]
done

**Comment by Thilakraj1998** [comment]
can we include the mentioned eigen value specturm plot

**Comment by arpitsomani8** [comment]
done

**Comment by Thilakraj1998** [comment]
changes required:
1. keep all import statement in top code cell with other imports
2. remove redundant variable in eigengap functions
3. move the eigengap analysis above model description(keep it separate from model initialization to reduce reading time on model section)
4. increase figure size of eigengap plot
5. reduce comments in eigengap functions (instead provide a summarized description in markdown cell above both the functions)

**Comment by arpitsomani8** [comment]
All changes done

**Comment by Thilakraj1998** [comment]
according to top 5 cluster value from eigengap analysis, the n_cluster must be 6 instead of 5 right ??

**Comment by arpitsomani8** [comment]
done

**Comment by Thilakraj1998** [comment]
what if we change some of the code line:
try to changes in this lines:

affinity_matrix = dists * dists
affinity_matrix = -affinity_matrix / local_scale

convert this to:
affinity_matrix = -(dists**2)/ local_scale

or

affinity_matrix = -pow(dists,2)/ local_scale

This will increase code efficiency and memory consumption

**Comment by arpitsomani8** [comment]
done and results are matching to the current one

**Comment by Thilakraj1998** [comment]
> done and results are matching to the current one

Does it works same for other datasets

**Comment by arpitsomani8** [comment]
> 
> 
> > done and results are matching to the current one
> 
> Does it works same for other datasets

Yes its working fine, i checked it with 3 different clustering dataset's.

**Comment by Thilakraj1998** [comment]
try running on Iris dataset
data source: https://raw.githubusercontent.com/Thilakraj1998/Datasets_general/main/Iris.csv

**Comment by Thilakraj1998** [comment]
the optimal number of cluster to select returned is not appropriate for this dataset

**Comment by arpitsomani8** [comment]
Iris dataset working fine, you can check this jupyter file here, and giving finest top 5 opimal number of clusters.

https://colab.research.google.com/drive/1fcrJ8XPGw_qQRWn4uApQPmmNTinGFcAo?usp=sharing

**Comment by Thilakraj1998** [comment]
is there any way to decide which optimal cluster to select from the top 5 cluster counts

**Comment by arpitsomani8** [comment]
simply take top1 instead top 5
check same jupyter file again...
but i think a choice of top 5 would be great. As to watch/read greater number of clusters in graph would be tough, of there is only single choice despite of top1.

**Comment by Thilakraj1998** [comment]
> simply take top1 instead top 5
> check same jupyter file again...
> but i think a choice of top 5 would be great. As to watch/read greater number of clusters in graph would be tough, of there is only single choice despite of top1.

what if we keep top 10 and sort them in ascending order

**Comment by arpitsomani8** [comment]
> 
> 
> > simply take top1 instead top 5
> > check same jupyter file again...
> > but i think a choice of top 5 would be great. As to watch/read greater number of clusters in graph would be tough, of there is only single choice despite of top1.
> 
> what if we keep top 10 and sort them in ascending order

it will also work fine
check the same jupyter file again...
if all good, just tell me, so i can add final code to repo.

**Comment by Thilakraj1998** [comment]
add one statement in the print :

top 10 Optimal number of clusters

**Comment by arpitsomani8** [comment]
done

**Pull request merged**
