### PR TITLE
Kindly let me know if any changes required. 

### PR DESCRIPTION
**Pull request by iamgrootsh7**
Decision tree_Robustscaler

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
required changes:
1. keep all import statements at the top together. instead of inbetween
2. clear the output for pip command cell.

**Comment by iamgrootsh7** [comment]
i have made the changes. is it okay now ?

**Comment by Thilakraj1998** [comment]
For all the files keep all the import statements at the top. instead of in between code cell .

**Comment by iamgrootsh7** [comment]
> For all the files keep all the import statements at the top. instead of in between code cell .

Can you please be more specific? I think it is correctly filled.  I just followed the existing template

**Comment by Thilakraj1998** [comment]
> > For all the files keep all the import statements at the top. instead of in between code cell .
> 
> Can you please be more specific? I think it is correctly filled. I just followed the existing template

In the Scale template you have import statement in the code cell. put that statements to the beginning of file along with other imports

**Comment by iamgrootsh7** [comment]
> > > For all the files keep all the import statements at the top. instead of in between code cell .
> > 
> > 
> > Can you please be more specific? I think it is correctly filled. I just followed the existing template
> 
> In the Scale template you have import statement in the code cell. put that statements to the beginning of file along with other imports

Sorry, I read import as short form for imporatnt. My bad

**Pull request merged**
