### PR TITLE
added LassoRegression_Scaled.ipynb

### PR DESCRIPTION
**Pull request by Sbhawal**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
hey snehaan,
I have mentioned few change related to all current and previous work in slack channel.
Just add a new markdown cell below title for meta description .which previously you would fill in Gsheet. and keep the required package text in another separate markdown cell below meta description

**Comment by Sbhawal** [comment]
Done, please check if okay 
thanks

**Comment by Thilakraj1998** [comment]
There is one extra code cell below filepath just remove it.
rename the file from LassoRegression_Scaled to LassoRegression_StandardScaler.

**Comment by Sbhawal** [comment]
done

**Pull request merged**
