### PR TITLE
GaussianNB_StandardScaler.ipynb Added

### PR DESCRIPTION
**Pull request by JayShimpi22**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
hey jay,
overall codes looks good.
following changes are required:
1. remove the output for installation process.
2. reduce the text size for title standard Scaler and for reference,near model section .
3. remove blank code cell in the bottom

**Comment by JayShimpi22** [comment]
Removed the output for every cell and resized the text wherever mentioned.

**Comment by Thilakraj1998** [comment]
Dont remove output from all the cells, just remove it for the pip command cell

**Comment by JayShimpi22** [comment]
Removed Output and made mentioned changes.

**Pull request merged**
