### PR TITLE
 Decision Tree Classifier with Standard Scaler 

### PR DESCRIPTION
**Pull request by iamgrootsh7**
Kindly let me know if any changes required. Sorry I accidentally deleted the file, so I closed the pull request.

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Hello there,
Required Changes:

1. Remove Description provide in Files heading just keep it "Decision Tree Classification with Standard Scalar"
2. Reduce detail provided in Scaling section for StandardScaler keep it max 2-3 lines.
3. change the section title from "Scaling " to "Data Scaling" or "Data Rescaling"
4. keep all import statements required in the complete process/code in a single code cell to make it cleaner.
5. Currently your code is not utilizing the **Scaled** data for training. you perform scaling on dataset or dataframe which will utilized for training and testing. for reference:
image

**Comment by iamgrootsh7** [comment]
I have made the required changes. Let me know if any further changes are required

**Comment by Thilakraj1998** [comment]
Change the font style to normal instead of bold in description of data scaling

**Comment by iamgrootsh7** [comment]
Yes finished

**Comment by iamgrootsh7** [comment]
I have completed the required changes. PLease let me know if there are any changes further. I will proceed for the next template.

**Comment by Thilakraj1998** [comment]
go for next one.

**Pull request merged**
