### PR TITLE
added BernoulliNB_StandardScaler

### PR DESCRIPTION
**Pull request by Sbhawal**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
hey,
Add few line of description for Standscaler near Model section. description should be max 2-3 line.

**Comment by Sbhawal** [comment]
Please check if the brief added is suitable or further correction is required.
Thanks

**Comment by Thilakraj1998** [comment]
reduce the text size for heading Rescaling and change it to Data Rescaling or Data Scaling

**Comment by Sbhawal** [comment]
Do.ne

**Comment by Thilakraj1998** [comment]
Add meta description for the code in the Gsheet

**Comment by Sbhawal** [comment]
Added description, please check.
If not upto the mark can you write me down what is required as a sample for this first one.
thanks.

**Comment by Thilakraj1998** [comment]
👍

**Pull request merged**
