### PR TITLE
SGDRegressor with RobustScaler

### PR DESCRIPTION
**Pull request by DSAishwaryaG**
SGDRegressor with RobustScaler and also with slight modification in graph code

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Hey Aishwarya,
can we convert the if else section which in the graphs section to a single line code.

**Comment by DSAishwaryaG** [comment]
i converted sir

**Comment by Thilakraj1998** [comment]
I mean to say in ternary expression like this :
n=len(x_test) if len(x_test)<20 else 20

**Comment by DSAishwaryaG** [comment]
yeah sir ! i did it yesterday but didn't save the changes properly.i will recommit now

**Comment by DSAishwaryaG** [comment]
Changes are made sir

**Comment by Thilakraj1998** [comment]
Just add  small description about RobustScaler near model section markdown

**Comment by Thilakraj1998** [comment]
in the bottom of the file there is one extra blank cell just remove it.
Make sure when you commit there no extra blank cell or typos

**Comment by Thilakraj1998** [comment]
Remove this Blank cell under creator section

**Comment by DSAishwaryaG** [comment]
i removed it sir !

**Pull request merged**
