### PR TITLE
AffinityPropagation.ipynb added

### PR DESCRIPTION
**Pull request by JayShimpi22**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
image
??
is this required or where you testing some code part

**Comment by Thilakraj1998** [comment]
image
This descriptions have TYPOS.

**Comment by Thilakraj1998** [comment]
put the seaborn import will together with other in single code cell

**Comment by JayShimpi22** [comment]
> image
> ??
> is this required or where you testing some code part

Yes, It was for testing the code,I will remove it

**Pull request closed without merging**
