### PR TITLE
added RobustScaler for KMeans Algorithm

### PR DESCRIPTION
**Pull request by viratchowdary21**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Hey virat,
Try to keep the code template generalized for multiple dataset. the currently your code is specialized for single dataset. Refer the reference code available on standardScaler kmeans.

**Comment by viratchowdary21** [comment]
I've made changes. Would you mind taking a look at them

**Comment by Thilakraj1998** [comment]
If you want, you can add the seasborn pair plot at the bottom

**Comment by Thilakraj1998** [comment]
for the pair plot let the seaborn library use default markers. since currently code will throw error on different number of clusters
and create individual pull request for each files

**Pull request closed without merging**
