### PR TITLE
Updated PolynomialRegression_Scale.ipynb

### PR DESCRIPTION
**Pull request by JayShimpi22**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Meta Description is missing from all the files .
please add it in a new  markdown cell below title and keep required package text in different markdown cell for the files

**Comment by JayShimpi22** [comment]
Screenshot 2021-08-09 200914


A meta description is added, sir!

**Comment by Thilakraj1998** [comment]
in PolynomialReg_MinMax its missing

**Comment by JayShimpi22** [comment]
okay

**Comment by Thilakraj1998** [comment]
There is 1 extra Polynomial Regression file in you branch

**Comment by JayShimpi22** [comment]
I deleted all the branches except the main one, now is there any duplicate file still?

**Comment by Thilakraj1998** [comment]
Yes in the main branch
image
yellow marked file is extra

**Comment by Thilakraj1998** [comment]
done

**Pull request merged**
