### PR TITLE
AdaBoostRegressor_StandardScaler

### PR DESCRIPTION
**Pull request by surya2365**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
image
In this section following changes are required:
1. dont create extra variable for any action. try to reduce line of code.
2. reduce section title size
3. change section title from "Rescaling the Dataset" to Data Rescaling or Data Scaling.
4. Dont mention parameter of StandardScaler method. Instead provide Reference URL to API. This will make the document/template much clearner and easy to read.

**Comment by Thilakraj1998** [comment]
for following code :
scaler = StandardScaler()
X=scaler.fit_transform(X)
X=pd.DataFrame(X,columns=x)

write it has :
X_Scaled=StandardScaler().fit_transform(X)
X=pd.DataFrame(X_Scaled,columns=x)

**Comment by Thilakraj1998** [comment]
Hey,
next time when ever you create new files please create or upload those inside appropriate file location.

**Comment by surya2365** [comment]
Yea sure, I'll do that, I'm just a bit confused about how to send a pull request and all.

**Pull request merged**
