### PR TITLE
Updated  codes with all scalers

### PR DESCRIPTION
**Pull request by devVipin01**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Hey vipin,
just update all the title in files according to Gsheet mentioned title column,
and new markdown cell  and add meta description into which before you had to fill in Gsheet.
keep title ,metadescription, and required package text in 3 different markdown cells

**Comment by Thilakraj1998** [comment]
hey vipin,
following changes are required:
1. Remove blank code cell in the bottom of the files
2. 
image

for this part keep the code as
X= df[features]
Y=df[target]

**Comment by Thilakraj1998** [comment]
There are Typos in description of scaling techniques
and
still code is wrong for features selection part

X=df.drop([Features],axis=1) is wrong

write it these way

X= df[feature]

**Comment by devVipin01** [comment]
Okay but I didn't get, "There are Typos in description of scaling techniques" this statement what changes I need to make

**Comment by Thilakraj1998** [comment]
image
This part has TYPOs
and some wrong statements
 And the model description is wrong current files has  for random forest instead of Gradient Boosting

**Pull request merged**
