### PR TITLE
RidgeClassifier with Scale

### PR DESCRIPTION
**Pull request by PrajwalNimje1997**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Prajwal,
dont submit file for wrong directory

**Comment by Thilakraj1998** [comment]
add meta descriptions in files refer some the already submitted files.

**Comment by PrajwalNimje1997** [comment]
Sir, I don't know what is exactly happening. What I mean is I have created a new branch name"scale1" and  added file name "RidgeClassifier_Scale.ipynb " in the location "ds-seed/Classification/Linear Models/ ". And then made a merge pull request.
Also I have added meta description in the file.
Then I don't know why it isn't visible to you.
I am new in github, please help me out. Is there anything I am doing wrong?

**Comment by Thilakraj1998** [comment]
check your slack

**Pull request closed without merging**
