### PR TITLE
added LocallyLinearEmbedding with StandardScaler

### PR DESCRIPTION
**Pull request by viratchowdary21**

### CODE REVIEW

**Comment by viratchowdary21** [comment]
made changes correct me if I'm wrong

**Comment by Thilakraj1998** [comment]
changes required:
1. numpy import redundant 

Question:
does explained variance really help in case of manifold algorithm?

**Comment by viratchowdary21** [comment]
Basically, locally linear embedding is a series of principal component analyses that then are compared spatially to determine the best embedding. If Explained Variance work on  PCA then it might work for LLE also. correct me if I'm wrong!

**Comment by viratchowdary21** [comment]
Would you like me to add anything else?

**Comment by viratchowdary21** [comment]
All my notebooks have already been updated.

**Pull request merged**
