### PR TITLE
Added LinearRegression_MinMaxScaler

### PR DESCRIPTION
**Pull request by mohityogesh44**
Code template for Linear Regression and feature scaling using  MinMax Scaler.

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Change the text style of parameter detail for MinMaxScaler to default to match files consistency.

**Comment by mohityogesh44** [comment]
> Change the text style of parameter detail for MinMaxScaler to default to match files consistency.
Changes Applied.

**Comment by Thilakraj1998** [comment]
Remove parameter details about MinMaxScaler . Instead just provide a URL to API.

**Comment by mohityogesh44** [comment]
Added reference to MinMaxScaler API.

**Comment by Thilakraj1998** [comment]
👍

**Pull request merged**
