### PR TITLE
 PolynomialRegression_RobustScaler.ipynb Added

### PR DESCRIPTION
**Pull request by JayShimpi22**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
goodmorning jay,
Just meta description to both the files

**Comment by JayShimpi22** [comment]
Added Meta description on excel sheet

**Comment by Thilakraj1998** [comment]
Polynomial regression
because polynomialfeatures are not passed to linear regression for training. please check at referene example of polynomial regression for better understanding how polynomial regression is performed.

**Comment by JayShimpi22** [comment]
Done

**Comment by Thilakraj1998** [comment]
In Ridge Regressor with PowerTransformer use pipeline.
currently transformer data is not passed to the model

**Comment by Thilakraj1998** [comment]
create separate pull request for polynomial regression files those are correct. just remove features .filepath and target specified to the variable.

**Comment by JayShimpi22** [comment]
Okay!

**Pull request closed without merging**
