### PR TITLE
Created the file for RandomForestRegressor with StandardScaler

### PR DESCRIPTION
**Pull request by Viraj-Jayant**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Hello Viraj, Just put the data scaling procedure into a complete different code cell above the model training or before spitting dataset

**Comment by Viraj-Jayant** [comment]
> Hello Viraj, Just put the data rescaling procedure into a complete different code cell above the model training or before spitting dataset
> And provide a detail about the procedure.
> For Reference:
> image

Hi, added the required section to the concerned file.

**Comment by Thilakraj1998** [comment]
try the file with different dataset and change the output

**Comment by Viraj-Jayant** [comment]
> try the file with different dataset and change the output

Please refer to the latest commit for the changed output/dataset.

**Pull request merged**
