### PR TITLE
added LocallyLinearEmbedding

### PR DESCRIPTION
**Pull request by viratchowdary21**

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Can we know how to select number of components for this algorithm.

**Comment by viratchowdary21** [comment]
image
sir, I got the graph like this, which one do I have to select i.e: high variance, low or just like elbow method (sudden bend)

**Comment by Thilakraj1998** [comment]
is the elbow method correct for the manifold algorithms ?

**Comment by viratchowdary21** [comment]
no no! not elbow method. there is a bend at the '5' right (in a curve)?   In simple, I'm asking you that should I consider 5 as optimal n_components.

**Comment by viratchowdary21** [comment]
I used the 'just like elbow method', not stated certainly elbow method

**Comment by Thilakraj1998** [comment]
> no no! not elbow method. there is a bend at the '5' right (in a curve)? In simple, I'm asking you that should I consider 5 as optimal n_components.

yes you have to select number at steep slope which in this case is 5

**Comment by Thilakraj1998** [comment]
> I used the 'just like elbow method', not stated certainly elbow method

sorry for confusion , its an scree plot not elbow method.

but is it valid approach for selection for component in LLE .

**Comment by viratchowdary21** [comment]
sir, I don't how to make a Scree plot with LLE, since eigenvalues need at least a 2-dimensional array. I can use reshape but an odd number of elements are present. I was not allowed to sue PCA or SVD. can you please help me out?

**Comment by Thilakraj1998** [comment]
> sir, I don't how to make a Scree plot with LLE, since eigenvalues need at least a 2-dimensional array. I can use reshape but an odd number of elements are present. I was not allowed to sue PCA or SVD. can you please help me out?

the current plot which you have plotted in the code is scree plot.

**Comment by Thilakraj1998** [comment]
image
this description is for  cumulative explained variance ratio , while your plot is for explained variance ratio.

**Comment by viratchowdary21** [comment]
i read in this blog that
image
ref:
https://ostwalprasad.github.io/machine-learning/PCA-using-python.html

**Comment by Thilakraj1998** [comment]
> i read in this blog that
> image
> ref:
> https://ostwalprasad.github.io/machine-learning/PCA-using-python.html

and your plot does the same work doesn't it ?

**Comment by viratchowdary21** [comment]
I didn't use any eigenvalue concept here. 
what I did is->
just find the variance of each fold (component) and then find the ratio of each component over a fold and then find the mean of each fold variance.

**Comment by Thilakraj1998** [comment]
when you calculate explained variance to mean your are finding eigen value for the decomposed data

**Comment by viratchowdary21** [comment]
Then it is the eigenvalues that I do not know much about, thank you for explaining.

**Comment by Thilakraj1998** [comment]
yes,
try to plot the explained variance directly instead of taking Mean of the explained variance, and see what the results are.

**Comment by viratchowdary21** [comment]
In this case, there is no difference since each component has the same variance.
image

**Comment by Thilakraj1998** [comment]
Okay

**Comment by Thilakraj1998** [comment]
can you send me this code file on personal slack, wanna test something

**Comment by Thilakraj1998** [comment]
hey, for the part of scree plot you should remove the description which mentions about cumulative explained variance

**Pull request merged**
