### PR TITLE
Create SVR_RobustScaler.ipynb

### PR DESCRIPTION
**Pull request by SaharshLaud**
SVR with Robust Scaler rescaling

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Hey Saharsh, Add few line of description for RobustScaler and also try few other datasets

**Comment by SaharshLaud** [comment]
Good Morning sir,
I'll add the description line and also if you could provide 3 to 4 standard
data sets to be used on all problems that would be really helpful.

**Comment by Thilakraj1998** [comment]
Hey, you can use the dataset for this repo: https://github.com/Thilakraj1998/Datasets_general.
just make sure that you are using right dataset for problem type. Currently don't use any dataset which require text preprocessing problems.

**Comment by SaharshLaud** [comment]
Thanks for the help, I will make sure not to use datasets which require
text preprocessing problems.

**Comment by SaharshLaud** [comment]
I have made the necessary changes

**Comment by Thilakraj1998** [comment]
Hey,
Change the RobustScaler() to Data Scaling or Data ReScaling in smaller size compared to Model

**Comment by SaharshLaud** [comment]
Changes have been applied.

**Pull request merged**
