### PR TITLE
Ridge Regressor with Robust Scaler and Pipeline upload

### PR DESCRIPTION
**Pull request by PrajwalNimje1997**
The Ridge Regressor is created. The template includes the Ridge Regressor with Robust Scaler. Also the pipeline is implemented.

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
Reduce text size for accuracy region for R2 and creator section

**Review by PrajwalNimje1997 — COMMENTED** [review]
I have done the necessary changes.Kindly look into it.

**Comment by Thilakraj1998** [comment]
change the file name to match the given filename in gsheet

**Comment by PrajwalNimje1997** [comment]
Sir,
I have changed the name, but I am not able to open the ipynb file now. its
not loading, only raw file is visible.
Also my merge pull request is accepted, but I am not able to see the my
file on the following github account: blobcity/ds-seed.

**Comment by Thilakraj1998** [comment]
Still the file names are wrong. please the Ghsheet filename section for proper name.

**Comment by PrajwalNimje1997** [comment]
Sir,
I am writing the name which was given in spreadsheet. Can you tell if I am writing the name from correct file, because I think there is some misunderstanding for me about which gsheet you are talking about.
I am attaching the proof as screenshot of the topic name from the google spreadsheet I received. Kindly see the attachment below.

Screenshot 2021-07-31 at 1 27 03 PM

**Comment by Thilakraj1998** [comment]
> Sir,
> I am writing the name which was given in spreadsheet. Can you tell if I am writing the name from correct file, because I think there is some misunderstanding for me about which gsheet you are talking about.
> I am attaching the proof as screenshot of the topic name from the google spreadsheet I received. Kindly see the attachment below.
> 
> Screenshot 2021-07-31 at 1 27 03 PM

there is column name Filename in the shit at the right side

**Comment by PrajwalNimje1997** [comment]
I have renamed it with the file name.

**Comment by Thilakraj1998** [comment]
You have push the file into wrong director. RidgeClassifier into Regression Folder. Be carefull while managing directors for appropriate algorithms and problem type

**Comment by PrajwalNimje1997** [comment]
ds-seed/Regression/Linear Models/
I have push in the above given directory right?
If not, can you please tell where to push?

**Comment by PrajwalNimje1997** [comment]
Ok, I got it. I have to put under classification. Will be done correct from next time.

**Pull request merged**
